add LDFLAGS: -ltinfo to go-libedit (#42)
Necessary for building on Gentoo for whatever reason; otherwise:

```
# github.com/cockroachdb/cockroach/pkg/cmd/cockroach-oss
/home/iliana/sdk/go1.22.11/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/go-link-2930997610/000077.o: undefined reference to symbol 'tgetstr'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```